### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by zhangcaifu** [DeepGraphLearning/graphvite#25] opened 2019-09-17 05:51 UTC
When I finished installing the code, I met a problem about the cuda version.
Here's the `conda list graphvite` :
Name                    Version                   Build  Channel
graphvite                 0.1.0           py36cuda100hbecf2fe    milagraph
The error message is :
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Check failed: error == cudaSuccess CUDA error CUDA driver version is insufficient for CUDA runtime version at /lustre04/scratch/zhuzhaoc/conda/conda-bld/graphvite_1566255529276/work/include/core/solver.h:182
*** Check failure stack trace: ***
    @     0x7f9580fec4dd  google::LogMessage::Fail()
    @     0x7f9580ff4071  google::LogMessage::SendToLog()
    @     0x7f9580febecd  google::LogMessage::Flush()
    @     0x7f9580fed76a  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f95851ba079  graphvite::CudaCheck()
    @     0x7f95852d21c5  graphvite::SolverMixin<>::SolverMixin()
    @     0x7f9585310775  _ZZN8pybind1112cpp_function10initializeIZNS_6detail8initimpl11constructorIJSt6vectorIiSaIiEEimEE7executeINS_6class_IN9graphvite11GraphSolverILm128EfjEEJEEEJNS_10call_guardIJNS_18gil_scoped_releaseEEEENS_5arg_vESI_SI_ELi0EEEvRT_DpRKT0_EUlRNS2_16value_and_holderES7_imE_vJSQ_S7_imEJNS_4nameENS_9is_methodENS_7siblingENS2_24is_new_style_constructorESH_SI_SI_SI_EEEvOSJ_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES17_
    @     0x7f9585240019  pybind11::cpp_function::dispatcher()
    @     0x562683ee6c54  _PyCFunction_FastCallDict
    @     0x562683ee706f  _PyObject_FastCallDict
    @     0x562683eebaa3  _PyObject_Call_Prepend
    @     0x562683ee6a5e  PyObject_Call
    @     0x562683f3f9eb  slot_tp_init
    @     0x562683f6edf7  type_call
    @     0x562683ee6a5e  PyObject_Call
    @     0x562683f92e37  _PyEval_EvalFrameDefault
    @     0x562683f67e66  _PyEval_EvalCodeWithName
    @     0x562683f69598  _PyFunction_FastCallDict
    @     0x562683ee701f  _PyObject_FastCallDict
    @     0x562683eebaa3  _PyObject_Call_Prepend
    @     0x562683f28b6e  slot_tp_new
    @     0x562683f6eda5  type_call
    @     0x562683ee6e3b  _PyObject_FastCallDict
    @     0x562683f6918a  _PyObject_FastCallKeywords
    @     0x562683f6ec0e  call_function
    @     0x562683f9251c  _PyEval_EvalFrameDefault
    @     0x562683f699b9  PyEval_EvalCodeEx
    @     0x562683f6a75c  PyEval_EvalCode
    @     0x562683fea744  run_mod
    @     0x562683feab41  PyRun_FileExFlags
    @     0x562683fead43  PyRun_SimpleFileExFlags
    @     0x562683fee833  Py_Main
Aborted (core dumped)
What can I do to solve it?

**Comment by KiddoZhu** [comment] 2019-09-17 16:23
Duplicate of #11 

Please check whether your CUDA version is consistent with graphvite's.

**Closed** 2019-11-29 03:36 UTC
