### ISSUE TITLE
entity_prediction error message can't recognize entities or relation

### ISSUE THREAD

**Issue by gustavopuma** [DeepGraphLearning/graphvite#50] opened 2020-03-10 19:35 UTC
when using the python interface and calling the method entity_prediction passing as parameter a array like that 
app1.entity_prediction(H=["Laura Little"],R=["hasTasks"],T=["Act as advisers to student organizations."],target="head", k=3)
to predict "HEAD"  I receive this message:

assert len(new_R) == len(R), "Can't recognize some entities or relations

when I use a file with the folowing file indicated into the property file_name works as expected no message: 
hasTechnology_Skills,Autodesk AutoCAD
hasTechnology_Skills,Navzilla
hasTechnology_Skills,Laboratory information management system LIMS
hasTasks,Stock cabinets or serving areas with condiments and refill condiment containers.
hasTasks,Evaluate and grade students' class work_ laboratory work_ assignments_ and papers. with this format:

no problem to do the same with TAIL.

**Comment by KiddoZhu** [comment] 2020-03-11 00:38
Duplicate of #49

**Closed** 2020-04-27 18:44 UTC
