### ISSUE TITLE
CUDA version error

### ISSUE THREAD

**Issue by joshuia** [DeepGraphLearning/graphvite#15] opened 2019-08-19 06:31 UTC
Hi, my env is: `conda list graphvite`
Name                    Version                   Build  Channel
graphvite                 0.1.0                py27cuda92    milagraph
`nvcc -V`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88

But when I run `graphvite baseline quick start`
it shows:
running baseline: quick_start.yaml
loading graph from /home/users/shiyixuan/.graphvite/dataset/blogcatalog/blogcatalog_train.txt
0.00018387%
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Graph<uint32>
------------------ Graph -------------------
#vertex: 10312, #edge: 333983
as undirected: yes, normalization: no
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[time] GraphApplication.load: 0.512994 s
Check failed: error == cudaSuccess CUDA error CUDA driver version is insufficient for CUDA runtime version at /lustre04/scratch/zhuzhaoc/conda/conda-bld/graphvite_1565206157156/work/include/core/solver.h:182
*** Check failure stack trace: ***
    @     0x7f740a1144dd  google::LogMessage::Fail()
    @     0x7f740a11c071  google::LogMessage::SendToLog()
    @     0x7f740a113ecd  google::LogMessage::Flush()
    @     0x7f740a11576a  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7408d290b9  graphvite::CudaCheck()
    @     0x7f7408e41105  graphvite::SolverMixin<>::SolverMixin()
    @     0x7f7408e7f6b5  _ZZN8pybind1112cpp_function10initializeIZNS_6detail8initimpl11constructorIJSt6vectorIiSaIiEEimEE7executeINS_6class_IN9graphvite11GraphSolverILm128EfjEEJEEEJNS_10call_guardIJNS_18gil_scoped_releaseEEEENS_5arg_vESI_SI_ELi0EEEvRT_DpRKT0_EUlRNS2_16value_and_holderES7_imE_vJSQ_S7_imEJNS_4nameENS_9is_methodENS_7siblingENS2_24is_new_style_constructorESH_SI_SI_SI_EEEvOSJ_PFT0_DpT1_EDpRKT2_ENUlRNS2_13function_callEE1_4_FUNES17_
    @     0x7f7408dae469  pybind11::cpp_function::dispatcher()
    @     0x7f7411f8d973  PyObject_Call
    @     0x7f7411f9c80d  instancemethod_call
    @     0x7f7411f8d973  PyObject_Call
    @     0x7f7411fe6764  slot_tp_init

Is that means cuda version error? And "/lustre04/scratch/zhuzhaoc/conda/conda-bld/graphvite_1565206157156/work/include/core/solver.h", this path is not mine.

**Comment by KiddoZhu** [comment] 2019-08-19 14:44
It seems that conda always install the latest cudatoolkit by default. Try the following line

```
conda install -c milagraph graphvite cudatoolkit=9.2
```

**Comment by KiddoZhu** [comment] 2019-08-19 14:45
Duplicate of #11

**Comment by joshuia** [comment] 2019-08-20 02:24
Thanks, But it seems not cudatoolkit version? `conda list cudatoolkit` shows: 
cudatoolkit               9.2                           0    defaults

**Comment by joshuia** [comment] 2019-08-20 02:28
#11 is my issue too, sorry for that I closed it incorrectly

**Comment by KiddoZhu** [comment] 2019-08-20 17:54
Could you show me your version of `cudatoolkit` and `graphvite`?

To my knowledge, they should be the same CUDA version according to conda's mechanism. Specifying the version for `cudatoolkit` will result in the corresponding version of `graphvite`.

**Comment by BuddhaZhang** [comment] 2019-08-26 04:55
Hello, I met same question.

conda list graphvite
# packages in environment at /home/zrg/anaconda3:
#
# Name           Version               Build Channel
graphvite       0.1.0               py37cuda92hbecf2fe    milagraph

conda list cudatoolkit
# packages in environment at /home/zrg/anaconda3:
#
# Name           Version               Build Channel
cudatoolkit      9.2                       0

**Comment by fjkfwz** [comment] 2019-08-30 23:38
same question.
```
conda list graphvite
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
graphvite                 0.1.0           py36cuda100hbecf2fe    milagraph
```

```
cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  410.48  Thu Sep  6 06:36:33 CDT 2018
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
```
```
conda list cudatoolkit
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
cudatoolkit               10.0.130                      0
```

**Closed** 2019-12-30 03:24 UTC
