### ISSUE TITLE
make error: An implementation of BLAS is required but none was found.

### ISSUE THREAD

**Issue by shiqiaodeng** [DeepGraphLearning/graphvite#26] opened 2019-09-23 02:14 UTC
hi!

When I was trying to install it from source I got error when make
`make`

The error message is as follow:
```checking if sgemm_ is being linked in already... no
checking for sgemm_ in -lmkl_intel_lp64... no
checking for sgemm_ in -lmkl... no
checking for sgemm_ in -lopenblas... no
checking for ATL_xerbla in -latlas... no
checking for sgemm_ in -lblas... no
checking for sgemm_ in -framework vecLib... no
checking for sgemm_ in -lcxml... no
checking for sgemm_ in -ldxml... no
checking for sgemm_ in -lscs... no
checking for sgemm_ in -lcomplib.sgimath... no
checking for sgemm_ in -lblas... (cached) no
checking for sgemm_ in -lblas... (cached) no
configure: error: An implementation of BLAS is required but none was found.
make[2]: *** [faiss/src/faiss-stamp/faiss-configure] Error 1
make[1]: *** [CMakeFiles/faiss.dir/all] Error 2
make: *** [all] Error 2
```
Any idea why this is happening? How can I get around this problem?

**Comment by KiddoZhu** [comment] 2019-09-23 02:43
Duplicate of #17 

It's because faiss can't find the dependency. I am not sure how to solve that, since I never meet this in my environment. A workaround is to comment out all faiss related lines in CMakeLists.txt, if you don't need to use the visualization. Otherwise please refer to the above issue.

**Comment by shiqiaodeng** [comment] 2019-09-28 12:05
Thank for you reply!Please forgive me for being busy with other things and not replying to you.
I have solved this problem according to your method.
`manually install OpenBLAS
compile faiss from source
compile graphvite with cmake .. -DFAISS_PATH=/path/to/faiss/ && make`

But I have a new problem.When I was trying to install it from source I got error when executing
`python setup.py install`
I found that other people have encountered this problem.(#34) 
Your suggestion is  thart export the paths of gflags and glog into LD_LIBRARY_PATH.
But I did not solve this problem according to your suggestion.

My configuration：
`Centos 7
python 3.7
conda install glog and gflags
CUDA 10.0`

I am looking forward to your reply!Thanks!

**Closed** 2019-09-29 18:04 UTC
